USE ETRADE2
/*SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),
COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES
WHERE CITY='ADANA'

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),
COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES
WHERE CITY='İSTANBUL'
SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),
COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES
WHERE CITY='ANKARA'*/

--* FROM SALES
--MIN(AMOUNT),MAX(AMOUNT),COUNT(FICHENO),SUM(AMOUNT),AVG(AMOUNT) FROM SALES 
--ORDER BY AMOUNT
--SELECT *FROM SALES ORDER BY TOTALPRICE
--En Fazla Satış yapan 10 şehir
/*SELECT TOP 10
CITY,
SUM(TOTALPRICE) AS TOTALPRICE
/*MIN(TOTALPRICE) AS MINPRICE
,MAX(TOTALPRICE)AS MAXPRICE,
COUNT(FICHENO) AS ROWCOUNT_
,SUM(TOTALPRICE) AS TOTALPRICE,
AVG(TOTALPRICE) AVGPRICE*/
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC*/
-- Bir şehirdeki satış getirme
/*CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE

FROM SALES 
WHERE CITY='ANKARA'
GROUP BY CITY, DATE2
ORDER BY CITY, DATE2
*/
--UPDATE SALES SET DATE2=CONVERT(date,DATE_)
--SELECT CONVERT (DATETIME,'2019-01-01 08:07:24.000')
-- Günlere göre satış çağırma
/*SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
WHERE DATE2='2019-01-01'
GROUP BY DATE2,CITY
ORDER BY DATE2,SUM(TOTALPRICE),CITY DESC
*/
--MAĞZALARIN AYLARA GÖRE SATIŞ RAKAMLARINI GETİRME
/*
UPDATE SALES SET MONTHNAME_='01.OCAK' 
WHERE DATEPART(MONTH,DATE2)=1
UPDATE SALES SET MONTHNAME_='02.ŞUBAT' 
WHERE DATEPART(MONTH,DATE2)=2
UPDATE SALES SET MONTHNAME_='03.MART' 
WHERE DATEPART(MONTH,DATE2)=3
UPDATE SALES SET MONTHNAME_='04.NİSAN' 
WHERE DATEPART(MONTH,DATE2)=4
UPDATE SALES SET MONTHNAME_='05.MAYIS' 
WHERE DATEPART(MONTH,DATE2)=5
UPDATE SALES SET MONTHNAME_='06.HAZİRAN' 
WHERE DATEPART(MONTH,DATE2)=6
UPDATE SALES SET MONTHNAME_='07.TEMMUZ' 
WHERE DATEPART(MONTH,DATE2)=7
UPDATE SALES SET MONTHNAME_='08.AĞUSTOS' 
WHERE DATEPART(MONTH,DATE2)=8
UPDATE SALES SET MONTHNAME_='09.EYLÜL' 
WHERE DATEPART(MONTH,DATE2)=9
UPDATE SALES SET MONTHNAME_='10.EKİM' 
WHERE DATEPART(MONTH,DATE2)=10
UPDATE SALES SET MONTHNAME_='11.KASIM' 
WHERE DATEPART(MONTH,DATE2)=11
UPDATE SALES SET MONTHNAME_='12.ARALIK' 
WHERE DATEPART(MONTH,DATE2)=12
*/
-- AYLARA GÖRE SATIŞ
/*SELECT MONTHNAME_,CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY MONTHNAME_,SUM(TOTALPRICE) DESC */

--SELECT DATEPART(MONTH,'2019-08-02')
--kategori bazlı satış getirme
/*SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMAOUNT
FROM SALES  
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
*/
-- ŞEHİRLERİN AYLARA GÖRE MÜŞTERİLERİ VE SATIŞ YAPILAN ÜRNLER
/*SELECT 
CITY,
COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTUMER,
 COUNT(DISTINCT FICHENO) AS CUSTUMERCOUNT, 
COUNT(*) AS ITEMCOUNT

FROM SALES
WHERE MONTHNAME_='01.OCAK' 
GROUP BY CITY
ORDER BY CITY
*/
--BELLİ BİR CİRONUN ÜZERİNDE SATIŞ YAPAN MAĞZALARI GETİRME
SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE
,COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT
FROM SALES
GROUP BY CITY 
HAVING COUNT(DISTINCT CUSTOMERNAME)>500 AND
SUM(TOTALPRICE)>300000
ORDER BY SUM(TOTALPRICE) DESC

--WHERE CITY IN ('ANKARA','İSTANBUL','İZMİR','AYDIN','HATAY')