/*Veri Sorgulama*/
USE ETRADE 
SELECT
ID, CUSTOMERNAME, CITY, BIRTHDAY, DISTRICT, GENDER
FROM 
CUSTOMERS
/*Veri Girme */
INSERT INTO CUSTOMERS 
(CUSTOMERNAME,CITY,BIRTHDAY,DISTRICT,GENDER)
VAlUES
('MEHEMET ÖZAL' ,'ANTALYA','1990-12-21','ALANYA','E')

SELECT * FROM CUSTOMERS 

/* Yıl Olarak yaş baz alma + Update*/
UPDATE CUSTOMERS 
SET NATION='US', 
AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

/*Trancude: Tabloyu sıfırlar*/
Truncate TABLE CUSTUMERS
 /*WHERE ŞARTI*/
SELECT * FROM CUSTOMERS

WHERE CITY IN ('İZMİR','ANTALYA')

UPDATE CUSTOMERS SET GENDER = 'KADIN' WHERE GENDER='K'
