SELECT
DATEPART(YEAR,O.DATE_) AS YIL,
DATEPART(MONTH,O.DATE_) AS AY,
CASE 
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN'ŞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN'NİSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN'HAZİRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN'AĞUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN'EKİM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN'ARALIK'
END AS AYADI,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
--SELECT
--ITM.CATEGORY1,
--ITM.CATEGORY2,ITM.CATEGORY3,
----CT.CITY AS SEHIRADI,
--SUM (OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
--SUM (OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
--COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI,
--SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMABIRIMFIYAT

--SELECT
--	U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD,
--	CT.CITY IL,T.TOWN AS ILCE,D.DISTRICT AS SEMT,A.ADDRESSTEXT AS ACIKADDRES
--	,O.ID AS SIPARISID,O.DATE_ AS TARIH,O.TOTALPRICE AS TOPLAMTUTUTAR
--	,P.DATE_ AS ODEMETARIHI,P.APPROVECODE AS BANKAONAY,
--	I.DATE_ AS FATURATARIHI,I.CARGOFICHENO AS KARGOFISNO
--	,ITM.ITEMCODE AS URUNKODU,ITM.ITEMNAME AS URUNADI,
--	OD.AMOUNT AS MIKTAR,OD.UNITPRICE AS BIRIMFIYAT,
--	OD.LINETOTAL AS SATIRTOPLAMI
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID 
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)