SELECT
CASE
WHEN PAYMENTTYPE=1 THEN 'KREDİ KARTI'
WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESİ'
END ODEMETURU_ACIKLAMA,
CASE
WHEN DATEPART(MONTH,DATE_)=1 THEN'OCAK'
	WHEN DATEPART(MONTH,DATE_)=2 THEN'ŞUBAT'
	WHEN DATEPART(MONTH,DATE_)=3 THEN'MART'
	WHEN DATEPART(MONTH,DATE_)=4 THEN'NİSAN'
	WHEN DATEPART(MONTH,DATE_)=5 THEN'MAYIS'
	WHEN DATEPART(MONTH,DATE_)=6 THEN'HAZİRAN'
	WHEN DATEPART(MONTH,DATE_)=7 THEN'TEMMUZ'
	WHEN DATEPART(MONTH,DATE_)=8 THEN'AĞUSTOS'
	WHEN DATEPART(MONTH,DATE_)=9 THEN'EYLÜL'
	WHEN DATEPART(MONTH,DATE_)=10 THEN'EKİM'
	WHEN DATEPART(MONTH,DATE_)=11 THEN'KASIM'
	WHEN DATEPART(MONTH,DATE_)=12 THEN'ARALIK'
END,
DATEPART(YEAR,DATE_),
DATEPART(MONTH,DATE_) AS AY,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS

GROUP BY DATEPART(MONTH,DATE_),DATEPART(YEAR,DATE_),PAYMENTTYPE
ORDER BY DATEPART(MONTH,DATE_),DATEPART(YEAR,DATE_),PAYMENTTYPE