--subquery
SET STATISTICS IO ON
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) 
AS ENDUSUKFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID)
 AS ENYUKSEKFIYAT,
 (SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID)
 AS ORTALAMAFIYAT,
  (SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID)
 AS TOPLAMADET,
 (SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID DESC)SONADDRES,
  (SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID)SONADDRES,
   (SELECT  COUNT(ADDRESSTEXT) FROM ADDRESS WHERE USERID=U.ID)SONADDRES
FROM USERS U,
ITEMS ITM 
WHERE ITM.ID NOT IN 
(SELECT ITEMID FROM ORDERDETAILS)
ORDER BY 3