--ORTALAMA TESLİMAT SÜRESİ
SELECT
CT.CITY,
--DATEPART(YEAR,O.DATE_) AS YIL,
--DATEPART(MONTH,O.DATE_) AS AY,
--U.ID,U.NAMESURNAME,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORTALAMATESLIMAT,
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENKISATESLIMAT,
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENUZUNTESLIMAT,
SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_TUTARI,
COUNT(O.ID) AS SIPARISSAYISI
--O.ID AS SIPARISID,
--O.DATE_ AS SIPARISTARIHI,
--I.DATE_ AS FATURATARIHI,
--AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORTALAMA,
--MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENKISATESLIMAT,
--MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENUZUNTESLİMAT
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID 
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID

GROUP BY 
--U.ID,U.NAMESURNAME,
--DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_),
CT.CITY
ORDER BY 2 DESC 