/*SELECT * FROM CUSTOMERS
--WHERE CITY= 'ANKARA' AND DISTRICT = 'ÇANKAYA' 
--AND GENDER ='KADIN' 
WHERE  CITY ='İZMİR' 
AND GENDER='ERKEK' 
AND BIRTHDAY BETWEEN '19800101' AND '20000101'*/
--SELECT * FROM CUSTOMERS 
--UPDATE  CUSTOMERS SET  GENDER ='ERKEK' WHERE GENDER='E' 

--AND operatörü
/*SELECT *FROM CUSTOMERS
WHERE CITY ='İSTANBUL'
AND GENDER='ERKEK'
AND BIRTHDATE BETWEEN '19900101' AND '20000101'*/

/*OR operatörü*/
/*USE ETRADE
SELECT * FROM CUSTOMERS
WHERE 
 --NOT BIRTHDATE BETWEEN '19900101' AND '19981231'
 BIRTHDATE <='19900101' OR BIRTHDATE >='19981231'
-- BIRTHDATE BETWEEN '19900101' AND '19981231'
--BIRTHDATE <='19900101' AND BIRTHDATE>='19981231'
-- OR VE IN KARŞILAŞTIRMASI
/*WHERE --CITY IN('İSTANBUL ','İZMİR','BURSA')
CITY='İSTANBUL' OR CITY='İZMİR' or CITY='BURSA'*/
*/

--DISTINCT komutu
--SELECT DISTINCT CITY FROM CUSTOMERS
/*SELECT DISTINCT CITY, DISTRICT FROM CUSTOMERS
WHERE CITY='İSTANBUL'
*/
/*SELECT DISTINCT GENDER FROM CUSTOMERS 
WHERE CITY='İSTANBUL'*/
--SELECT DISTINCT AGE FROM CUSTOMERS
--WHERE CITY='İSTANBUL'

--ORDER BY komutu 
/*SELECT * FROM CUSTOMERS
WHERE CITY='İSTANBUL'
--ORDER BY CITY ASC , CUSTOMERNAME DESC
ORDER BY CITY , DISTRICT,CUSTOMERNAME */
-- TOP komutu kullanımı 
SELECT 
TOP 1 PERCENT
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME