-- PLS_INTEGER,BINARY_INTEGER,NUMBER
-- PLS_INTEGER,BINARY_INTEGER,NUMBER OVERFLOW(AŞIRI YÜKLEME)

DECLARE
P1 BINARY_INTEGER:=2147483647;
P2 NUMBER:=1;

n NUMBER;
BEGIN

    n:= P1+P2;
    DBMS_OUTPUT.PUT_LINE(n);
    DBMS_OUTPUT.PUT_LINE(TO_CHAR(n,'999,999,999,999,99'));
END;
