-- EXCEPTIONS 
SET SERVEROUTPUT ON;
/*DECLARE 
D NUMBER;
BEGIN
D:=BOLME(10,0);
DBMS_OUTPUT.PUT_LINE(D);
EXCEPTION WHEN ZERO_DIVIDE THEN
DBMS_OUTPUT.PUT_LINE(SQLERRM);

END;*/
SELECT * FROM departments;
DESC DEPARTMENTS;

DECLARE 
WADI VARCHAR2(30);
BEGIN
WADI:=BOLUM_ADI(2);
DBMS_OUTPUT.PUT_LINE(WADI);
END;
