CREATE OR REPLACE FUNCTION 
BOLUM_ADI(P_BOLUMNO IN NUMBER)RETURN VARCHAR2
IS
WBOLUM_ADI VARCHAR2(30);
BEGIN
SELECT DEPARTMENT_NAME INTO WBOLUM_ADI FROM DEPARTMENTS
WHERE DEPARTMENT_ID=P_BOLUMNO;

RETURN(WBOLUM_ADI);
END;
