--CONNECT olan kullanıcıları bulma kodu
SELECT USERNAME,SID,SERIAL#,TYPE FROM V$SESSION
WHERE TYPE<> 'BACKGROUND';
-- RESTRICTED SESSION ROLUNE SAHİP KULLANICILAR LİSTELEME
SELECT DR.GRANTEE FROM DBA_SYS_PRIVS  DS ,DBA_ROLE_PRIVS DR 
WHERE ds.PRIVILEGE ='RESTRICTED SESSION'
AND DS.GRANTEE = DR.GRANTED_ROLE
UNION

SELECT USERNAME FROM DBA_SYS_PRIVS DS , DBA_USERS DU
WHERE ds.PRIVILEGE ='RESTRICTED SESSION'
AND DS.GRANTEE = DU.USERNAME;

-- Script
CREATE OR REPLACE VIEW KILL_SESSION AS
SELECT 'ALTER SYSTEM KILL SESSION ''' || SID || ','||SERIAL#|| ''' IMMEDIATE;' KILL_SORGU FROM V$SESSION WHERE TYPE<> 'BACKGROUND'
AND USERNAME NOT IN
(SELECT DR.GRANTEE FROM DBA_SYS_PRIVS  DS ,DBA_ROLE_PRIVS DR 
WHERE ds.PRIVILEGE ='RESTRICTED SESSION'
AND DS.GRANTEE = DR.GRANTED_ROLE
UNION
SELECT USERNAME FROM DBA_SYS_PRIVS DS , DBA_USERS DU
WHERE ds.PRIVILEGE ='RESTRICTED SESSION'
AND DS.GRANTEE = DU.USERNAME);

SELECT * FROM KILL_SESSION;